name: Deploy iOS to Firebase App Distribution

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.4'
          channel: 'stable'

      - name: Install flutter dependencies
        run: flutter pub get

      - name: iOS build action
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          output-path: app-release.ipa
          project-path: ios/Runner.xcodeproj
          workspace-path: ios/Runner.xcworkspace
          code-signing-identity: Apple Distribution
          export-method: ad-hoc
          team-id: ${{ secrets.IOS_TEAM_ID }}
          p12-base64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          mobileprovision-base64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ipa
          path: app-release.ipa

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: ipa

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.IOS_FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: ipa/app-release.ipa