name: Deploy Android to Firebase App Distribution

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup dependencies cache
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.4'
          channel: 'stable'

      - name: Install flutter dependencies
        run: flutter pub get

      # release用にkeystoreを設定する場合は以下をコメントイン
      # - name: Setup signing config
      #   run: |
      #     echo '${{ secrets.ANDROID_KEYSTORE_BASE64 }}' | base64 -d > android/release.keystore
      #     export KEYSTORE_PASSWORD='${{ secrets.ANDROID_KEYSTORE_PASSWORD }}'
      #     export KEY_ALIAS='${{ secrets.ANDROID_KEY_ALIAS }}'
      #     export KEY_PASSWORD='${{ secrets.ANDROID_KEY_PASSWORD }}'

      - name: Build apk
        run: flutter build apk --release --build-number=$GITHUB_RUN_NUMBER

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: apk/app-release.apk